#===============================================================================
# ONTOQA Configuration File
#===============================================================================

#===============================================================================
# Ontology
#===============================================================================
ontologyPath: "data/knowledge/organizationNew-gm.ttl"
ontologyFormat: "TURTLE"

#===============================================================================
# Lexicon
#===============================================================================
grammarPath: "data/grammar/organizationNew-gm.json"
grammarFormat: "JSON"
