#===============================================================================
# ONTOQA Configuration File
#===============================================================================

#===============================================================================
# Ontology
#===============================================================================
ontologyPath: !resolveString "${RES}/knowledge/sample.ttl"
ontologyFormat: "TURTLE"

#===============================================================================
# Lexicon
#===============================================================================
lexiconPath: !resolveString "${RES}/lexicon/sample.lexicon.rdf"
lexiconFormat: "RDFXML"
