#===============================================================================
# ONTOQA Configuration File
#===============================================================================

#===============================================================================
# Ontology
#===============================================================================
ontologyPath: "data/knowledge/organization.ttl"
ontologyFormat: "TURTLE"

#===============================================================================
# Lexicon
#===============================================================================
grammarPath: "data/grammar/sltag.json"
grammarFormat: "JSON"
