#===============================================================================
# ONTOQA Configuration File
#===============================================================================

#===============================================================================
# Ontology
#===============================================================================
ontologyPath: "data/knowledge/sample.ontology.ttl"
ontologyFormat: "TURTLE"

#===============================================================================
# Lexicon
#===============================================================================
grammarPath: "data/lexicon/sample.lexicon.rdf"
grammarFormat: "RDFXML"
