#===============================================================================
# ONTOQA Configuration File
#===============================================================================

#===============================================================================
# Ontology
#===============================================================================
ontologyPath: !resolveString "${PWD}/data/knowledge/sample.ttl"
ontologyFormat: "TURTLE"

#===============================================================================
# Lexicon
#===============================================================================
lexiconPath: !resolveString "${PWD}/data/lexicon/sample.lexicon.rdf"
lexiconFormat: "RDFXML"
