#===============================================================================
# ONTOQA Configuration File
#===============================================================================

#===============================================================================
# Ontology
#===============================================================================
ontologyPath: "data/knowledge/organization.ttl"
ontologyFormat: "TURTLE"

#===============================================================================
# Lexicon
#===============================================================================
grammarPath: "data/lexicon/organization.rdf"
grammarFormat: "RDFXML"
