#===============================================================================
# ONTOQA Configuration File
#===============================================================================

#===============================================================================
# Ontology
#===============================================================================
ontologyPath: "data/knowledge/organizationVersion2.ttl"
ontologyFormat: "TURTLE"

#===============================================================================
# Lexicon
#===============================================================================
grammarPath: "data/grammar/organization.json"
grammarFormat: "JSON"
