#===============================================================================
# ONTOQA Configuration File
#===============================================================================

#===============================================================================
# Ontology
#===============================================================================
#ontologyPath: "${RES}/knowledge/sample.ttl"
#ontologyFormat: "TURTLE"

#===============================================================================
# Lexicon
#===============================================================================
#lexiconPath: "${RES}/lexicon/sample.lexicon.rdf"
#lexiconFormat: "RDFXML"
