#===============================================================================
# ONTOQA Configuration File
#===============================================================================

#===============================================================================
# Ontology
#===============================================================================
#ontologyPath: !templateString "${PROJECT_RESOURCES}/knowledge/sample.ttl"
#ontologyFormat: "TURTLE"

#===============================================================================
# Lexicon
#===============================================================================
#lexiconPath: !templateString "${PROJECT_RESOURCES}/knowledge/sample.lexicon.ldp"
#lexiconFormat: "RDFXML"
